services:
  files:
    hostname: ${SYNCTHING_HOSTNAME:?err}
    image: syncthing/syncthing:latest
    network_mode: host
    restart: always
    volumes:
      - ./data-files:/var/syncthing

  rclone:
    command: >
      -c "apk add gpg &&
          tar --create --file=/tmp/Files.tgz --gzip [!config]* &&
          gpg --batch --cipher-algo AES256 --output /tmp/Files.tgz.gpg --passphrase-file /config/rclone/gpg_passphrase.txt --symmetric /tmp/Files.tgz;
          rclone copy $(find -name *.kdbx -type f) remote:;
          rclone copy /tmp/Files.tgz.gpg remote:"
    entrypoint: sh
    image: rclone/rclone:latest
    network_mode: host
    profiles:
      - disabled
    volumes:
      - ./data-files:/data:ro
      - ./data-rclone:/config/rclone
