services:
  files:
    hostname: ${SYNCTHING_HOSTNAME:?err}
    image: syncthing/syncthing:latest
    network_mode: host
    restart: always
    volumes:
      - ./data-files:/var/syncthing

  rclone:
    command: >
      -c "rclone copy $(find -not -path '*/.*' -name '*.kdbx' -type f) remote:;
          apk add --no-cache gnupg &&
          tar --create --file /tmp/Files.tar [!config]* &&
          gpg --batch --cipher-algo AES256 --output /tmp/Files.tar.gpg --passphrase-file /config/rclone/gpg_passphrase.txt --symmetric /tmp/Files.tar &&
          rclone copy /tmp/Files.tar.gpg remote:"
    entrypoint: sh
    image: rclone/rclone:latest
    network_mode: host
    profiles:
      - disabled
    volumes:
      - ./data-files:/data:ro
      - ./data-rclone:/config/rclone
